---
- name: Sample Access Policy
  hosts: localhost
  gather_facts: false
  vars:
    aci_host: 198.18.133.200
    aci_username: admin
    aci_password: C1sco12345
  
  tasks:
  - name: Create Policy Group for VPCs
    aci_interface_policy_leaf_policy_group:
        host: '{{ aci_host }}'
        username: '{{ aci_username }}'
        password: '{{ aci_password }}'
        validate_certs: no
        lag_type: node
        policy_group: '{{ item }}'
        link_level_policy: 10G_Auto
        cdp_policy: CDP_Enabled
        lldp_policy: LLDP_Enabled
        port_channel_policy: LACP_Enabled
        aep: Servers_AAEP
        state: present
    with_sequence: start=1 end=2 format=Sample%02d


  - name: Create Policy Group for PCs
    aci_interface_policy_leaf_policy_group:
        host: '{{ aci_host }}'
        username: '{{ aci_username }}'
        password: '{{ aci_password }}'
        validate_certs: no
        lag_type: link
        policy_group: '{{ item }}'
        link_level_policy: 10G_Auto
        cdp_policy: CDP_Enabled
        lldp_policy: LLDP_Enabled
        port_channel_policy: LACP_Enabled
        aep: Servers_AAEP
        state: present
    with_sequence: start=1 end=2 format=SamplePC%02d